export type RiskFactor =
  | 'VERY_LOW_MOOD'
  | 'LOW_MOOD'
  | 'NEUTRAL_MOOD'
  | 'EXTREME_CRAVINGS'
  | 'HIGH_CRAVINGS'
  | 'MODERATE_CRAVINGS'
  | 'MULTIPLE_TRIGGERS'
  | 'SEVERAL_TRIGGERS'
  | 'SINGLE_TRIGGER'
  | 'SUPPORT_REQUESTED'
  | 'FELT_UNSAFE'
  | 'CONCERNING_NOTES'
  | 'RELAPSE_LANGUAGE';